<x-app-layout>
    @php($questions=data_get($attempt->content_snapshot,'activity.modality')==='paper' ? collect() : collect($attempt->content_snapshot['questions'] ?? [])) @php($saved=$attempt->responses->keyBy('snapshot_question_key'))
    <x-slot name="header"><h1 class="text-3xl font-black text-duo-heading">{{ data_get($attempt->content_snapshot,'activity.title',$activity->title) }}</h1></x-slot>
    <form method="POST" action="{{ route('student.pedagogical.activities.save',[$activity,$attempt]) }}" class="mx-auto max-w-4xl space-y-5">@csrf
        @forelse($questions as $index=>$question) @php($value=data_get($saved->get($question['key'])?->answer,'value'))
            <fieldset class="rounded-2xl border-2 border-duo-border bg-white p-6"><legend class="px-2 text-lg font-extrabold">Questão {{ $index+1 }}</legend><p class="mb-4 whitespace-pre-wrap">{{ data_get($question,'content.statement','Sem enunciado') }}</p>
                @if(!empty($question['resources']))<aside class="mb-4 space-y-3 rounded-xl border-2 border-blue-200 bg-blue-50 p-4" aria-label="Materiais de apoio">@foreach($question['resources'] as $resource) @php($mime=(string)data_get($resource,'file.mime_type','')) @php($hasFile=filled(data_get($resource,'file.storage_path'))) @php($url=$hasFile?route('student.pedagogical.activities.resource',[$activity,$attempt,$question['key'],$resource['resource_version_id']]):null)<section><h3 class="font-extrabold">{{ $resource['title'] }}</h3>@if(filled(data_get($resource,'content.body')))<p class="whitespace-pre-wrap">{{ data_get($resource,'content.body') }}</p>@endif @if($url && str_starts_with($mime,'image/'))<a href="{{ $url }}" target="_blank" rel="noopener"><img class="mt-2 max-h-96 rounded-lg" src="{{ $url }}" alt="{{ data_get($resource,'content.alt_text',$resource['title']) }}"></a>@elseif($url)<a class="mt-2 inline-flex min-h-11 items-center font-bold text-blue-800 underline" href="{{ $url }}" target="_blank" rel="noopener">Baixar arquivo de apoio</a>@endif @if(filled(data_get($resource,'content.external_url')))<a class="mt-2 block break-all font-bold text-blue-800 underline" href="{{ data_get($resource,'content.external_url') }}" target="_blank" rel="nofollow noopener">Abrir fonte externa</a>@endif</section>@endforeach</aside>@endif
                @if($question['type']==='multiple_choice')<div class="space-y-2">@foreach(data_get($question,'content.options',[]) as $optionIndex=>$option)<label class="flex min-h-11 items-center gap-3 rounded-xl border p-3"><input type="radio" name="answers[{{ $question['key'] }}]" value="{{ $optionIndex }}" @checked((string)$value===(string)$optionIndex)><span>{{ $option }}</span></label>@endforeach</div>
                @elseif($question['type']==='true_false')<div class="flex gap-3">@foreach(['1'=>'Verdadeiro','0'=>'Falso'] as $optionValue=>$label)<label class="flex min-h-11 items-center gap-2 rounded-xl border p-3"><input type="radio" name="answers[{{ $question['key'] }}]" value="{{ $optionValue }}" @checked((string)$value===(string)$optionValue)> {{ $label }}</label>@endforeach</div>
                @else<textarea class="input-field w-full" rows="6" name="answers[{{ $question['key'] }}]">{{ $value }}</textarea>@endif
            </fieldset>
        @empty <div class="rounded-2xl border-2 border-duo-border bg-white p-6"><p>Confirme a realização desta atividade conforme as instruções.</p></div> @endforelse
        <div class="flex flex-wrap gap-3"><button class="duo-button-secondary min-h-11 rounded-xl px-6 py-3 font-extrabold">Salvar progresso</button><button formaction="{{ route('student.pedagogical.activities.submit',[$activity,$attempt]) }}" class="duo-button-primary min-h-11 rounded-xl px-6 py-3 font-extrabold">Enviar atividade</button></div>
    </form>
</x-app-layout>
