<x-app-layout>
    <x-slot name="header"><h1 class="text-3xl font-black text-duo-heading">{{ $lesson->exists ? 'Editar aula' : 'Nova aula' }}</h1></x-slot>
    <form method="POST" action="{{ $lesson->exists ? route('lessons.update',$lesson) : route('lessons.store') }}" class="mx-auto max-w-5xl space-y-6 rounded-2xl border-2 border-duo-border bg-white p-6">@csrf @if($lesson->exists) @method('PUT') @endif
        <div class="grid gap-4 md:grid-cols-2"><label class="font-bold">Título<input class="input-field mt-1 w-full" name="title" value="{{ old('title',$lesson->title) }}" required></label><label class="font-bold">Disciplina<select class="input-field mt-1 w-full" name="discipline_id"><option value="">Geral</option>@foreach($disciplines as $discipline)<option value="{{ $discipline->id }}" @selected(old('discipline_id',$lesson->discipline_id)==$discipline->id)>{{ $discipline->name }}</option>@endforeach</select></label></div>
        <label class="block font-bold">Objetivos<textarea class="input-field mt-1 w-full" rows="3" name="objectives">{{ old('objectives',$lesson->objectives) }}</textarea></label>
        <label class="block font-bold">Conteúdo da aula<textarea class="input-field mt-1 w-full" rows="10" name="content">{{ old('content',$lesson->content) }}</textarea></label>
        <fieldset><legend class="font-extrabold">Turmas</legend><div class="mt-2 grid gap-2 sm:grid-cols-2">@foreach($classes as $class)<label class="rounded-xl border p-3"><input type="checkbox" name="class_ids[]" value="{{ $class->id }}" @checked(in_array($class->id,old('class_ids',$lesson->schoolClasses->pluck('id')->all())))> {{ $class->name }}</label>@endforeach</div></fieldset>
        <div class="grid gap-4 md:grid-cols-2"><label class="font-bold">Data da aula<input type="datetime-local" class="input-field mt-1 w-full" name="starts_at" value="{{ old('starts_at',$lesson->starts_at?->format('Y-m-d\TH:i')) }}"></label><label class="font-bold">Situação<select class="input-field mt-1 w-full" name="status"><option value="draft" @selected(old('status',$lesson->status)==='draft')>Rascunho</option><option value="published" @selected(old('status',$lesson->status)==='published')>Publicada</option><option value="archived" @selected(old('status',$lesson->status)==='archived')>Arquivada</option></select></label></div>
        <label class="flex gap-3 rounded-xl bg-sky-50 p-4"><input type="checkbox" name="generate_review" value="1" @checked(old('generate_review',$lesson->generate_review))><span><strong>Gerar rascunho de revisão</strong><br><span class="text-sm text-gray-600">O professor poderá revisar, complementar ou importar exercícios por JSON.</span></span></label>
        <div class="flex gap-3"><button class="duo-button-primary rounded-xl px-6 py-3 font-extrabold">Salvar aula</button><a href="{{ route('lessons.index') }}" class="duo-button-secondary rounded-xl px-6 py-3 font-bold">Voltar</a></div>
    </form>
</x-app-layout>
