@php $statusLabels=['pending'=>'Pendentes','in_review'=>'Em análise','approved'=>'Aprovadas','rejected'=>'Rejeitadas','withdrawn'=>'Retiradas','removed'=>'Removidas','all'=>'Todas']; @endphp
<x-app-layout>
    <x-slot name="header"><div><p class="text-sm font-bold text-primary">Administração global</p><h1 class="page-title">Moderação do catálogo público</h1><p class="mt-1 text-sm text-gray-600">Fila global, denúncias e trilha de decisão independente.</p></div></x-slot>
    <nav class="mb-6 flex flex-wrap gap-2" aria-label="Estados das submissões">@foreach($statusLabels as $key=>$label)<a href="{{ route('admin.public-catalog.index',['status'=>$key]) }}" class="{{ $status===$key?'btn-primary':'btn-secondary' }} btn-sm" @if($status===$key) aria-current="page" @endif>{{ $label }}</a>@endforeach</nav>
    <section aria-labelledby="submissions-title"><h2 id="submissions-title" class="mb-3 text-xl font-extrabold">Submissões</h2><div class="space-y-3">@forelse($submissions as $submission)@php $snapshot=$submission->snapshot_json;$label=($snapshot['kind']??null)==='question'?data_get($snapshot,'content.statement','Questão'):data_get($snapshot,'title','Recurso'); @endphp<article class="card flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><div class="flex gap-2"><span class="badge badge-neutral">{{ $snapshot['kind']??'item' }}</span><span class="badge badge-warning">{{ $submission->status }}</span>@if($submission->duplicate_candidates_json)<span class="badge badge-danger">Similaridade sinalizada</span>@endif</div><h3 class="mt-2 font-extrabold">{{ $label }}</h3><p class="text-sm text-gray-600">{{ $submission->submitter->name }} · {{ $submission->submitted_at->timezone(config('app.timezone'))->format('d/m/Y H:i') }}</p></div><a href="{{ route('admin.public-catalog.show',$submission) }}" class="btn-primary btn-sm justify-center">Analisar</a></article>@empty<div class="card p-8 text-center text-gray-600">Nenhuma submissão neste estado.</div>@endforelse</div><div class="mt-5">{{ $submissions->links() }}</div></section>
    <section class="mt-10" aria-labelledby="reports-title"><h2 id="reports-title" class="mb-3 text-xl font-extrabold">Denúncias abertas</h2><div class="space-y-3">@forelse($reports as $report)<article class="card p-5"><div class="flex flex-col gap-3 lg:flex-row lg:justify-between"><div><span class="badge badge-danger">{{ $report->reason_code }}</span><p class="mt-2 font-bold">{{ $report->details }}</p><p class="text-sm text-gray-600">Por {{ $report->reporter->name }} · {{ $report->created_at->timezone(config('app.timezone'))->format('d/m/Y H:i') }}</p></div><div class="grid gap-2 lg:w-96"><form method="POST" action="{{ route('admin.public-catalog.reports.resolve',$report) }}">@csrf<input type="hidden" name="decision" value="upheld"><label class="sr-only" for="uphold-{{ $report->id }}">Justificativa para acolher</label><textarea id="uphold-{{ $report->id }}" name="resolution" class="input-field text-sm" minlength="10" required placeholder="Justificativa verificável"></textarea><button class="btn-primary btn-sm mt-2 w-full justify-center" type="submit">Acolher e suspender</button></form><form method="POST" action="{{ route('admin.public-catalog.reports.resolve',$report) }}">@csrf<input type="hidden" name="decision" value="dismissed"><label class="sr-only" for="dismiss-{{ $report->id }}">Justificativa para descartar</label><textarea id="dismiss-{{ $report->id }}" name="resolution" class="input-field text-sm" minlength="10" required placeholder="Justificativa para descartar"></textarea><button class="btn-secondary btn-sm mt-2 w-full justify-center" type="submit">Descartar denúncia</button></form></div></div></article>@empty<div class="card p-8 text-center text-gray-600">Nenhuma denúncia aberta.</div>@endforelse</div><div class="mt-5">{{ $reports->links() }}</div></section>
    <section class="mt-10" aria-labelledby="reward-rules-title">
        <div class="mb-4 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between">
            <div><h2 id="reward-rules-title" class="text-xl font-extrabold">Recompensas por colaboração</h2><p class="text-sm text-gray-600">Regras imutáveis e versionadas. A aprovação concede créditos uma única vez, respeitando os tetos mensais.</p></div>
        </div>

        <form method="POST" action="{{ route('admin.public-catalog.reward-rules.store') }}" class="card grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-4">
            @csrf
            <div><label class="input-label" for="reward-name">Nome</label><input id="reward-name" name="name" class="input-field" maxlength="120" required value="{{ old('name') }}" placeholder="Questão pública aprovada"></div>
            <div><label class="input-label" for="reward-version">Versão</label><input id="reward-version" name="rule_version" class="input-field" maxlength="50" pattern="[A-Za-z0-9._-]+" required value="{{ old('rule_version') }}" placeholder="2026-08-v1"></div>
            <div><label class="input-label" for="reward-kind">Conteúdo</label><select id="reward-kind" name="subject_kind" class="input-field" required><option value="question">Questão</option><option value="resource" @selected(old('subject_kind')==='resource')>Recurso</option></select></div>
            <div><label class="input-label" for="reward-resource">Crédito</label><select id="reward-resource" name="resource_key" class="input-field" required><option value="monthly_questions_created">Questões criadas</option><option value="monthly_exam_publications">Publicações de avaliação</option><option value="monthly_omr_scans">Leituras OMR</option></select></div>
            <div><label class="input-label" for="reward-amount">Créditos por aprovação</label><input id="reward-amount" name="credit_amount" class="input-field" type="number" min="1" max="1000000" required value="{{ old('credit_amount',1) }}"></div>
            <div><label class="input-label" for="reward-user-cap">Teto por colaborador/mês</label><input id="reward-user-cap" name="per_user_monthly_cap" class="input-field" type="number" min="1" max="1000000" required value="{{ old('per_user_monthly_cap',10) }}"></div>
            <div><label class="input-label" for="reward-global-cap">Teto global/mês (opcional)</label><input id="reward-global-cap" name="global_monthly_cap" class="input-field" type="number" min="1" max="100000000" value="{{ old('global_monthly_cap') }}"></div>
            <div class="grid grid-cols-2 gap-2"><div><label class="input-label" for="reward-start">Início</label><input id="reward-start" name="starts_at" class="input-field" type="datetime-local" value="{{ old('starts_at') }}"></div><div><label class="input-label" for="reward-end">Fim</label><input id="reward-end" name="ends_at" class="input-field" type="datetime-local" value="{{ old('ends_at') }}"></div></div>
            <div class="md:col-span-2 xl:col-span-4"><button class="btn-primary" type="submit">Criar versão em rascunho</button></div>
        </form>

        <div class="mt-4 space-y-3">
            @forelse($rewardRules as $rule)
                <article class="card flex flex-col gap-3 p-5 lg:flex-row lg:items-center lg:justify-between">
                    <div><div class="flex flex-wrap gap-2"><span class="badge badge-neutral">{{ $rule->subject_kind }}</span><span class="badge {{ $rule->status==='active'?'badge-success':($rule->status==='draft'?'badge-warning':'badge-neutral') }}">{{ $rule->status }}</span><span class="badge badge-neutral">{{ $rule->rule_version }}</span></div><h3 class="mt-2 font-extrabold">{{ $rule->name }}</h3><p class="text-sm text-gray-600">{{ $rule->credit_amount }} crédito(s) em {{ $rule->resource_key }} · teto individual {{ $rule->per_user_monthly_cap }} · teto global {{ $rule->global_monthly_cap ?? 'sem teto' }} · {{ $rule->awards_count }} decisão(ões)</p></div>
                    <div>@if($rule->status==='draft')<form method="POST" action="{{ route('admin.public-catalog.reward-rules.activate',$rule) }}">@csrf<button class="btn-primary btn-sm" type="submit">Ativar versão</button></form>@elseif(in_array($rule->status,['active','scheduled'],true))<form method="POST" action="{{ route('admin.public-catalog.reward-rules.retire',$rule) }}">@csrf<button class="btn-secondary btn-sm" type="submit">Aposentar</button></form>@endif</div>
                </article>
            @empty
                <div class="card p-8 text-center text-gray-600">Nenhuma recompensa configurada. Aprovações continuam sem efeito financeiro até uma regra ser ativada.</div>
            @endforelse
        </div>
        <div class="mt-5">{{ $rewardRules->links() }}</div>
    </section>
</x-app-layout>
