@php $snapshot=$submission->snapshot_json;$isQuestion=($snapshot['kind']??null)==='question';$title=$isQuestion?data_get($snapshot,'content.statement','Questão'):data_get($snapshot,'title','Recurso'); @endphp
<x-app-layout>
    <x-slot name="header"><div class="page-header"><div><nav class="breadcrumb"><a href="{{ route('admin.public-catalog.index') }}">Moderação</a><span class="material-symbols-outlined text-[16px]" aria-hidden="true">chevron_right</span><span class="current">Submissão #{{ $submission->id }}</span></nav><h1 class="page-title">Analisar submissão</h1></div><span class="badge badge-warning">{{ $submission->status }}</span></div></x-slot>
    <div class="grid gap-6 xl:grid-cols-[1fr_24rem]">
        <div class="space-y-5"><section class="card p-6"><p class="text-xs font-extrabold uppercase text-primary">{{ $isQuestion?'Questão':'Recurso' }}</p><h2 class="mt-2 text-xl font-extrabold">{{ $title }}</h2>@if($isQuestion)<div class="mt-4 space-y-2">@foreach(data_get($snapshot,'content.options',[]) as $index=>$option)<p class="rounded-lg border p-3 text-sm {{ (int)data_get($snapshot,'content.correct_option',-1)===$index?'border-primary bg-primary/5':'' }}">{{ chr(65+$index) }}. {{ $option }}</p>@endforeach</div>@else<p class="mt-4 whitespace-pre-line text-sm text-gray-700">{{ data_get($snapshot,'version.content.body','Recurso baseado em arquivo.') }}</p>@if(data_get($snapshot,'version.storage_path'))<a class="btn-secondary btn-sm mt-4" href="{{ route('admin.public-catalog.evidence',$submission) }}">Baixar evidência privada</a>@endif @endif</section>
            <section class="card p-6"><h2 class="text-lg font-extrabold">Direitos e origem</h2><dl class="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt class="text-gray-500">Autor</dt><dd class="font-bold">{{ $submission->submitter->name }} · {{ $submission->submitter->email }}</dd></div><div><dt class="text-gray-500">Base</dt><dd class="font-bold">{{ $submission->rights_basis }}</dd></div><div><dt class="text-gray-500">Termos</dt><dd class="font-bold">{{ $submission->terms_version }}</dd></div><div><dt class="text-gray-500">Atribuição</dt><dd class="font-bold">{{ $submission->attribution?:'Não informada' }}</dd></div></dl>@if($submission->rights_notes)<p class="mt-4 rounded-lg bg-gray-50 p-3 text-sm">{{ $submission->rights_notes }}</p>@endif @if($submission->evidence_url)<a class="mt-3 inline-block break-all text-sm font-bold text-primary" href="{{ $submission->evidence_url }}" rel="noopener noreferrer" target="_blank">Abrir evidência externa</a>@endif</section>
            @if($submission->duplicate_candidates_json)<section class="card border-amber-300 p-6"><h2 class="font-extrabold text-amber-900">Possíveis duplicatas</h2><p class="mt-2 text-sm">Submissões: {{ implode(', ',$submission->duplicate_candidates_json) }}. Similaridade é apenas sinal; confirme manualmente.</p></section>@endif
            <section class="card p-6"><h2 class="text-lg font-extrabold">Histórico</h2><ol class="mt-4 space-y-3 border-l-2 pl-4">@foreach($submission->events as $event)<li><p class="font-bold">{{ str_replace('_',' ',$event->action) }}</p><p class="text-sm text-gray-600">{{ $event->created_at->timezone(config('app.timezone'))->format('d/m/Y H:i') }} @if($event->actor)· {{ $event->actor->name }}@endif</p>@if($event->reason)<p class="text-sm">{{ $event->reason }}</p>@endif</li>@endforeach</ol></section></div>
        <aside class="space-y-4">@if($submission->status==='pending')<form method="POST" action="{{ route('admin.public-catalog.start',$submission) }}" class="card p-5">@csrf<button class="btn-secondary w-full justify-center" type="submit">Assumir análise</button></form>@endif @if(in_array($submission->status,['pending','in_review']))<form method="POST" action="{{ route('admin.public-catalog.decide',$submission) }}" class="card space-y-4 p-5">@csrf<div><label for="decision" class="input-label">Decisão</label><select id="decision" name="decision" class="input-field" required><option value="approved">Aprovar snapshot</option><option value="rejected">Rejeitar</option></select></div><div><label for="reason" class="input-label">Fundamentação</label><textarea id="reason" name="reason" rows="6" class="input-field" minlength="10" maxlength="5000" required></textarea></div><div><label for="duplicate_of_submission_id" class="input-label">Duplicata da submissão (opcional)</label><input id="duplicate_of_submission_id" name="duplicate_of_submission_id" type="number" min="1" class="input-field"></div><button class="btn-primary w-full justify-center" type="submit">Registrar decisão</button></form>@endif</aside>
    </div>
</x-app-layout>
