<x-app-layout>
    <x-slot name="header"><div class="flex flex-wrap items-end justify-between gap-3"><div><p class="text-sm font-bold text-primary-dark">Editor pedagógico</p><h1 class="text-3xl font-black text-duo-heading">{{ $revision->exists?'Editar revisão':'Nova revisão' }}</h1></div>@if($revision->exists)<div class="flex gap-2"><a class="duo-button-secondary rounded-xl px-4 py-2 font-bold" href="{{ route('revisions.prompt',$revision) }}">Gerar prompt para IA</a><a class="rounded-xl border px-4 py-2 font-bold" href="{{ route('revisions.report',$revision) }}">Relatório</a></div>@endif</div></x-slot>
    <div class="mx-auto max-w-7xl space-y-6">
        @if($canManage)
        <form method="POST" action="{{ $revision->exists?route('revisions.update',$revision):route('revisions.store') }}" class="space-y-5 rounded-2xl border-2 border-duo-border bg-white p-6">@csrf @if($revision->exists)@method('PUT')@endif
            <div class="grid gap-4 md:grid-cols-2"><label class="font-bold">Título<input class="input-field mt-1 w-full" name="title" value="{{ old('title',$revision->title) }}" required></label><label class="font-bold">Disciplina<select class="input-field mt-1 w-full" name="discipline_id"><option value="">Geral</option>@foreach($disciplines as $discipline)<option value="{{ $discipline->id }}" @selected(old('discipline_id',$revision->discipline_id)==$discipline->id)>{{ $discipline->name }}</option>@endforeach</select></label></div>
            <label class="block font-bold">Descrição<textarea class="input-field mt-1 w-full" name="description" rows="3">{{ old('description',$revision->description) }}</textarea></label>
            <fieldset><legend class="font-extrabold">Turmas</legend><div class="mt-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">@foreach($classes as $class)<label class="rounded-xl border p-3"><input type="checkbox" name="class_ids[]" value="{{ $class->id }}" @checked(in_array($class->id,old('class_ids',$revision->schoolClasses->pluck('id')->all())))> {{ $class->name }}</label>@endforeach</div></fieldset>
            <div class="grid gap-4 md:grid-cols-3"><label class="font-bold">Quando<select name="timing" class="input-field mt-1 w-full">@foreach(['before'=>'Antes da prova','after'=>'Depois da prova','independent'=>'Independente'] as $v=>$l)<option value="{{ $v }}" @selected(old('timing',$revision->timing?:'after')===$v)>{{ $l }}</option>@endforeach</select></label><label class="font-bold">Tentativas<input class="input-field mt-1 w-full" type="number" min="1" max="20" name="max_attempts" value="{{ old('max_attempts',$revision->max_attempts?:1) }}"></label><label class="font-bold">Feedback<select class="input-field mt-1 w-full" name="feedback_mode">@foreach(['immediate'=>'Imediato','end'=>'Ao final','hidden'=>'Oculto'] as $v=>$l)<option value="{{ $v }}" @selected(old('feedback_mode',$revision->feedback_mode?:'end')===$v)>{{ $l }}</option>@endforeach</select></label></div>
            <div class="grid gap-3 md:grid-cols-3"><label class="rounded-xl bg-sky-50 p-4"><input type="checkbox" name="is_required" value="1" @checked(old('is_required',$revision->is_required))> <strong>Obrigatória</strong></label><label class="rounded-xl bg-amber-50 p-4"><input type="checkbox" name="block_exam" value="1" @checked(old('block_exam',$revision->block_exam))> <strong>Bloquear início da prova</strong></label><label class="rounded-xl bg-violet-50 p-4"><input type="checkbox" name="gamification_enabled" value="1" @checked(old('gamification_enabled',$revision->gamification_enabled??true))> <strong>XP e conquistas</strong></label></div>
            <div class="grid gap-4 md:grid-cols-2"><label class="font-bold">Disponível em<input class="input-field mt-1 w-full" type="datetime-local" name="available_at" value="{{ old('available_at',$revision->available_at?->format('Y-m-d\TH:i')) }}"></label><label class="font-bold">Prazo<input class="input-field mt-1 w-full" type="datetime-local" name="due_at" value="{{ old('due_at',$revision->due_at?->format('Y-m-d\TH:i')) }}"></label></div>
            <button class="duo-button-primary rounded-xl px-6 py-3 font-extrabold">Salvar configurações</button>
        </form>
        @else
            <section class="rounded-2xl border-2 border-duo-border bg-white p-6"><h2 class="text-xl font-extrabold">Revisão enviada para análise</h2><p class="mt-2 text-gray-700">{{ $revision->description }}</p><p class="mt-3 text-sm font-bold">Autor: {{ $revision->author?->name }} · {{ $revision->items->count() }} itens</p></section>
        @endif

        @if($revision->exists)
            <section class="rounded-2xl border-2 border-duo-border bg-white p-6"><div class="flex flex-wrap justify-between gap-3"><div><h2 class="text-xl font-extrabold">Fluxo de publicação</h2><p class="text-sm text-gray-600">Situação atual: {{ str_replace('_',' ',ucfirst($revision->status)) }}</p></div></div><form class="mt-4 grid gap-3 md:grid-cols-[1fr_2fr_auto]" method="POST" action="{{ route('revisions.status',$revision) }}">@csrf<select class="input-field" name="status"><option value="in_review">Enviar para revisão</option><option value="published">Publicar</option>@if($canReview)<option value="changes_requested">Devolver para ajustes</option><option value="suspended">Suspender</option>@endif</select><input class="input-field" name="review_notes" placeholder="Observação opcional"><button class="duo-button-primary rounded-xl px-5 py-2 font-bold">Aplicar</button></form></section>

            @if($canManage)
            <section class="rounded-2xl border-2 border-duo-border bg-white p-6"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-xl font-extrabold">Itens da revisão</h2><p class="text-sm text-gray-600">Alterações publicadas chegam imediatamente; respostas já dadas preservam a versão respondida.</p></div><a href="{{ route('revisions.prompt',$revision) }}" class="duo-button-secondary rounded-xl px-4 py-2 font-bold">Importar da IA</a></div>
                <div class="mt-5 space-y-4">@foreach($revision->items as $item)<details class="rounded-xl border p-4"><summary class="cursor-pointer font-bold">#{{ $loop->iteration }} · {{ str_replace('_',' ',ucfirst($item->type)) }} — {{ Str::limit($item->prompt,90) }}</summary><form method="POST" action="{{ route('revisions.items.update',[$revision,$item]) }}" class="mt-4 grid gap-3">@csrf @method('PUT') @include('revisions.item-fields',['item'=>$item])<button class="duo-button-primary justify-self-start rounded-xl px-4 py-2 font-bold">Atualizar item</button></form><form method="POST" action="{{ route('revisions.items.destroy',[$revision,$item]) }}" class="mt-2">@csrf @method('DELETE')<button class="text-sm font-bold text-red-700">Remover item</button></form></details>@endforeach</div>
                <details class="mt-5 rounded-xl border-2 border-dashed p-4"><summary class="cursor-pointer font-extrabold">Adicionar item manualmente</summary><form method="POST" action="{{ route('revisions.items.store',$revision) }}" class="mt-4 grid gap-3">@csrf @include('revisions.item-fields',['item'=>new App\Models\RevisionItem(['type'=>'multiple_choice','difficulty'=>1,'points'=>1,'is_active'=>true])])<button class="duo-button-primary justify-self-start rounded-xl px-4 py-2 font-bold">Adicionar</button></form></details>
            </section>
            @endif
        @endif
    </div>
</x-app-layout>
