@php $statusLabels=['pending'=>'Pendente','in_review'=>'Em análise','approved'=>'Aprovada','rejected'=>'Rejeitada','withdrawn'=>'Retirada','removed'=>'Removida']; @endphp
<x-app-layout>
    <x-slot name="header"><div class="page-header"><div><h1 class="page-title">Minhas contribuições públicas</h1><p class="mt-1 text-sm text-gray-600">Histórico imutável de submissões, decisões e publicações.</p></div><div class="card px-5 py-3 text-center"><p class="text-xs font-bold text-gray-500">Reputação</p><p class="text-2xl font-black text-primary">{{ $reputation['score'] }}</p><p class="text-xs text-gray-500">{{ $reputation['events'] }} eventos verificados</p></div></div></x-slot>
    <div class="space-y-4">
        @forelse($submissions as $submission)
            @php $snapshot=$submission->snapshot_json; $label=($snapshot['kind']??null)==='question' ? data_get($snapshot,'content.statement','Questão') : data_get($snapshot,'title','Recurso'); @endphp
            <article class="card p-5"><div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div class="flex flex-wrap gap-2"><span class="badge badge-neutral">{{ ($snapshot['kind']??null)==='question'?'Questão':'Recurso' }}</span><span class="badge {{ $submission->status==='approved'?'badge-success':($submission->status==='rejected'||$submission->status==='removed'?'badge-danger':'badge-warning') }}">{{ $statusLabels[$submission->status]??$submission->status }}</span></div><h2 class="mt-3 font-extrabold text-duo-heading">{{ $label }}</h2><p class="mt-1 text-sm text-gray-600">Enviada em {{ $submission->submitted_at->timezone(config('app.timezone'))->format('d/m/Y H:i') }} · termos {{ $submission->terms_version }}</p>@if($submission->decision_reason)<p class="mt-3 rounded-lg bg-gray-50 p-3 text-sm"><strong>Decisão:</strong> {{ $submission->decision_reason }}</p>@endif</div>
                    @if(in_array($submission->status,['pending','in_review']))<form method="POST" action="{{ route('public-catalog.submissions.withdraw',$submission) }}" class="w-full sm:w-72">@csrf<label for="withdraw-{{ $submission->id }}" class="sr-only">Motivo da retirada</label><input id="withdraw-{{ $submission->id }}" name="reason" class="input-field !py-2 text-sm" minlength="10" maxlength="2000" required placeholder="Motivo da retirada"><button class="btn-secondary btn-sm mt-2 w-full justify-center" type="submit">Retirar submissão</button></form>@endif</div>
                <details class="mt-4"><summary class="cursor-pointer text-sm font-bold text-primary">Ver histórico</summary><ol class="mt-3 space-y-2 border-l-2 border-duo-border pl-4">@foreach($submission->events as $event)<li class="text-sm"><strong>{{ str_replace('_',' ',$event->action) }}</strong> · {{ $event->created_at->timezone(config('app.timezone'))->format('d/m/Y H:i') }} @if($event->actor)por {{ $event->actor->name }}@endif @if($event->reason)<p class="text-gray-600">{{ $event->reason }}</p>@endif</li>@endforeach</ol></details>
            </article>
        @empty<div class="card p-12 text-center"><span class="material-symbols-outlined text-5xl text-gray-300" aria-hidden="true">publish</span><h2 class="mt-3 text-xl font-extrabold">Nenhuma submissão</h2><p class="mt-2 text-gray-600">Envie uma questão ou recurso próprio pela respectiva biblioteca.</p></div>@endforelse
    </div>
    <div class="mt-6">{{ $submissions->links() }}</div>
</x-app-layout>
