<x-app-layout>
    <x-slot name="header"><h1 class="text-3xl font-black text-duo-heading">{{ $activity->exists ? 'Editar atividade' : 'Nova atividade' }}</h1></x-slot>
    <form method="POST" action="{{ $activity->exists ? route('activities.update',$activity) : route('activities.store') }}" class="mx-auto max-w-6xl space-y-6 rounded-2xl border-2 border-duo-border bg-white p-6">@csrf @if($activity->exists)@method('PUT')@endif
        <div class="grid gap-4 md:grid-cols-2"><label class="font-bold">Título<input class="input-field mt-1 w-full" name="title" value="{{ old('title',$activity->title) }}" required></label><label class="font-bold">Disciplina<select class="input-field mt-1 w-full" name="discipline_id"><option value="">Geral</option>@foreach($disciplines as $discipline)<option value="{{ $discipline->id }}" @selected(old('discipline_id',$activity->discipline_id)==$discipline->id)>{{ $discipline->name }}</option>@endforeach</select></label></div>
        <label class="block font-bold">Instruções<textarea class="input-field mt-1 w-full" rows="5" name="instructions">{{ old('instructions',$activity->instructions) }}</textarea></label>
        <fieldset><legend class="font-extrabold">Turmas</legend><div class="mt-2 grid gap-2 sm:grid-cols-2">@foreach($classes as $class)<label class="rounded-xl border p-3"><input type="checkbox" name="class_ids[]" value="{{ $class->id }}" @checked(in_array($class->id,old('class_ids',$activity->schoolClasses->pluck('id')->all())))> {{ $class->name }}</label>@endforeach</div></fieldset>
        <fieldset><legend class="font-extrabold">Questões (opcional)</legend><div class="mt-2 max-h-72 space-y-2 overflow-auto rounded-xl border p-3">@foreach($questions as $question)<label class="flex gap-2 rounded-lg p-2 hover:bg-sky-50"><input type="checkbox" name="question_ids[]" value="{{ $question->id }}" @checked(in_array($question->id,old('question_ids',$activity->questions->pluck('id')->all())))><span>{{ Str::limit($question->content['statement'] ?? 'Sem enunciado',130) }}</span></label>@endforeach</div></fieldset>
        <div class="grid gap-4 md:grid-cols-3"><label class="font-bold">Disponível em<input type="datetime-local" class="input-field mt-1 w-full" name="available_at" value="{{ old('available_at',$activity->available_at?->format('Y-m-d\TH:i')) }}"></label><label class="font-bold">Prazo<input type="datetime-local" class="input-field mt-1 w-full" name="due_at" value="{{ old('due_at',$activity->due_at?->format('Y-m-d\TH:i')) }}"></label><label class="font-bold">Tentativas<input type="number" min="1" max="20" class="input-field mt-1 w-full" name="max_attempts" value="{{ old('max_attempts',$activity->max_attempts?:1) }}"></label></div>
        <div class="grid gap-4 md:grid-cols-3"><label class="font-bold">Pontos<input type="number" step="0.01" min="0" class="input-field mt-1 w-full" name="points" value="{{ old('points',$activity->points?:0) }}"></label><label class="font-bold">Modalidade<select name="modality" class="input-field mt-1 w-full">@foreach(['online'=>'On-line','paper'=>'Impressa','hybrid'=>'Híbrida'] as $value=>$label)<option value="{{ $value }}" @selected(old('modality',$activity->modality)===$value)>{{ $label }}</option>@endforeach</select></label><label class="font-bold">Situação<select name="status" class="input-field mt-1 w-full">@foreach(['draft'=>'Rascunho','published'=>'Publicada','archived'=>'Arquivada'] as $value=>$label)<option value="{{ $value }}" @selected(old('status',$activity->status)===$value)>{{ $label }}</option>@endforeach</select></label></div>
        <label class="flex gap-3 rounded-xl bg-sky-50 p-4"><input type="checkbox" name="generate_review" value="1" @checked(old('generate_review',$activity->generate_review))><span><strong>Gerar rascunho de revisão desta atividade</strong></span></label>
        <button class="duo-button-primary rounded-xl px-6 py-3 font-extrabold">Salvar atividade</button>
    </form>
</x-app-layout>
